# -*- coding: utf-8 -*-
"""NAVIT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q4AUDRnvEdfVniHWdHgNA-oGMpBmd3qi
"""

import gspread, requests
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd
import pprint

scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive.file", "https://www.googleapis.com/auth/drive"]
creds = ServiceAccountCredentials.from_json_keyfile_name("client_secret.json", scope)

client = gspread.authorize(creds)
ss = client.open("NAVIT")

Monday = ss.get_worksheet(0)
Tuesday = ss.get_worksheet(1)
Wednesday = ss.get_worksheet(2)
Thursday = ss.get_worksheet(3)
Friday = ss.get_worksheet(4)
Class_references = ss.get_worksheet(5)
Node_details = ss.get_worksheet(6)

column1 = ["O", "A0", "B0", "C0", "D0", "G0", "J0", "H0", "Y0", "L", "S11", "S12", "S13", "M11", "M12", "M13", "A1", "B1", "C1", "D1", "G1", "J1", "LIB", "Y1", "S21", "S22", "S23", "M21", "M22", "M23", "LAB 1", "A2", "C2", "D2", "G2", "J2", "K2", "N2", "LAB2", "S31", "S32", "S33", "M31", "M32", "M33"]
column2 = ["Entrance", "AB001 - Coding Studio I", "AB002 - Coding Studio II", "AB003 - Coding Studio III", "AB004 - Faculty Cabin - Ground Floor", "AB005 - Computer Lab 1", "AB008 - Music Room - Auditorium Main", "Auditorium Back", "Conference Room", "Leftest Corner", "Stairs at AB003", "Stairs at Auditorium", "Stairs at SDC Office", "Stairs mid of Ground and 1st Floor at AB003", "Stairs mid of Ground and 1st Floor at Auditorium", "Stairs mid of Ground and 1st Floor at SDC Office", "AB101 - Math Studio I", "AB102 - Math Studio II", "AB103 - Math Studio II", "AB104 - Faculty Cabin - 1st Floor", "AB105 - Computer Lab 2", "AB108 - Joint - Examination Cabin", "Library ", "Unknown Lab", "Stairs at AB103", "Stairs at Examination Cabin", "Stairs at Library", "Stairs mid of 1st and 2nd Floor at AB103", "Stairs mid of 1st and 2nd Floor at Examination Cabin", "Stairs mid of 1st and 2nd Floor at Library", "AB201 - ECE Lab", "AB202 - Classroom", "AB203 - Engineering Drawing", "AB204 - Faculty Cabin - 2nd Floor", "AB205 - English Studio", "AB208 - Joint", "AB209 - Hall", "AB210 - Classroom", "AB211 - EEE Lab", "Stairs at Engineering Studio", "Stairs at AB209", "Stairs at ECE Lab", "Stairs mid of 2nd and 3rd Floor at Engineering Studio", "Stairs mid of 2nd and 3rd Floor at AB209", "Stairs End"]

index = 0
for index in range(len(column1)):
  Node_details.update_cell(index+1, 3, index+1)

index = 38
for index in range(len(column2)):
  Node_details.update_cell(index+1, 2, column2[index])

#indices of rooms available over university
Rooms = []

class Node:
  Node_name = str        #class or area name
  Node_number = int      #Unique class number
  Status = bool          # 0 for unavailable, 1 for unavaialble

  def __init__(self, name, number, St):
    self.Node_name = name
    self.Node_number = number
    self.Status = St

  def UpdateStatus(self, Changeto):
    self.Status = Changeto

class Person:
  Person_name = str
  Person_reg_number = str
  Person_timetable =

class TimeTable: